name: poc
networks:
  poc:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  processes-1:
    container_name: processes-1
    image: processes:latest
    entrypoint: ["/processes"]
    networks:
      poc:
        ipv4_address: 10.5.1.4
        aliases:
          - processes-1
    environment:
      - CLI_ID=1

  processes-2:
    container_name: processes-2
    image: processes:latest
    entrypoint: ["/processes"]
    networks:
      poc:
        ipv4_address: 10.5.1.5
        aliases:
          - processes-2
    environment:
      - CLI_ID=2

  processes-3:
    container_name: processes-3
    image: processes:latest
    entrypoint: ["/processes"]
    networks:
      poc:
        ipv4_address: 10.5.1.6
        aliases:
          - processes-3
    environment:
      - CLI_ID=3


  reviver-1:
    container_name: reviver-1
    image: reviver:latest
    entrypoint: ["/reviver"]
    networks:
      poc:
        ipv4_address: 10.5.1.1
    environment:
      - CLI_TOPOLOGY_NODES=3
      - CLI_ID=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./name_ip.csv:/name_ip.csv

  reviver-2:
    container_name: reviver-2
    image: reviver:latest
    entrypoint: ["/reviver"]
    networks:
      poc:
        ipv4_address: 10.5.1.2
    environment:
      - CLI_TOPOLOGY_NODES=3
      - CLI_ID=2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./name_ip.csv:/name_ip.csv
  reviver-3:
    container_name: reviver-3
    image: reviver:latest
    entrypoint: ["/reviver"]
    networks:
      poc:
        ipv4_address: 10.5.1.3
    environment:
      - CLI_TOPOLOGY_NODES=3
      - CLI_ID=3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./name_ip.csv:/name_ip.csv