name: poc
services:
  processes-1:
    container_name: processes-1
    image: processes:latest
    entrypoint: ["/processes"]
    networks:
      poc:
        aliases:
          - processes-1
    environment:
      - CLI_ID=2
      - LISTEN_PORT=8000

  processes-2:
    container_name: processes-2
    image: processes:latest
    entrypoint: ["/processes"]
    networks:
      poc:
        aliases:
          - processes-2
    environment:
      - CLI_ID=1
      - LISTEN_PORT=8000

networks:
  poc:
    driver: bridge
    internal: true
